#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# 私鐵手帳 · Next Stop — v1.1.1 雲端同步用 Cloudflare R2 設定精靈
#   產出：R2_ACCOUNT_ID／R2_BUCKET／R2_ACCESS_KEY_ID／R2_SECRET_ACCESS_KEY／R2_ENDPOINT
#   寫到：%LOCALAPPDATA%\NextStop\r2.env（repo 外；v1.1.1 的「同步」分頁與沙盒測試讀這裡）
#   不寫 GitHub secret（CI 不需要；同步在裝置端，不經伺服器）
#   依據：https://developers.cloudflare.com/r2/api/tokens/（2026-09 查閱）；bucket 頁按鈕用字若與畫面不同，跟著最接近的走。

ENV_FILE="${R2_ENV_FILE:-$(cygpath -u "$LOCALAPPDATA" 2>/dev/null || echo "$HOME")/NextStop/r2.env}"   # 蓋掉 library 的 .env 預設；要改路徑用 R2_ENV_FILE
mkdir -p "$(dirname "$ENV_FILE")"

TOTAL_STAGES=4

banner "Cloudflare R2 設定（私鐵手帳同步用）"

# ── Stage 1：登入＋開 R2＋抄 Account ID ─────────────────────────────────────
stage "Cloudflare：登入、開通 R2、抄 Account ID"
say "R2 是 Cloudflare 的物件儲存，免費層每月 10 GB、流出免費——同步的加密日誌會放這裡。"
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "登入 Cloudflare（沒帳號就註冊一個，免費）。"
step "左側選 Storage & databases › R2 › Overview。第一次會要求「開通 R2」——免費層也要走一次結帳流程綁卡，不會扣款。"
step "右側「Account Details」找到 Account ID（32 個十六進位字元），點旁邊的複製。"
note "找不到的話：瀏覽器網址列 dash.cloudflare.com/<這一串>/r2 中間那段就是 Account ID。"
ask R2_ACCOUNT_ID "貼上 Account ID："
while [[ ! "$R2_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]]; do
  warn "看起來不像 Account ID（應為 32 個 0-9a-f）。再貼一次？"
  ask R2_ACCOUNT_ID "貼上 Account ID："
done
pause "抄好了？按 Enter 進下一步"

# ── Stage 2：建 bucket ──────────────────────────────────────────────────────
stage "R2：建一個 bucket"
say "bucket 就是一個獨立的儲存桶；只給私鐵手帳用一個，之後 token 也只限這一桶。"
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "按「Create bucket」。"
step "Bucket name 建議填 next-stop-sync（只能小寫、數字、連字號，3–63 字）。"
step "Location 留「Automatic」即可；若有「Provide a location hint」可選 Asia-Pacific（APAC），不選也沒關係。"
step "其他選項不動，按「Create bucket」。"
ask R2_BUCKET "你建的 bucket 名稱（預設 next-stop-sync）："
[[ -z "$R2_BUCKET" ]] && R2_BUCKET="next-stop-sync"
while [[ ! "$R2_BUCKET" =~ ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$ ]]; do
  warn "名稱不合規則（小寫字母／數字／連字號，3–63 字，頭尾不能是連字號）。"
  ask R2_BUCKET "bucket 名稱："
done
pause "bucket 建好了？按 Enter 進下一步"

# ── Stage 3：建 API token（只限這一桶）──────────────────────────────────────
stage "R2：建 API token（Object Read & Write、只限這一桶）"
say "token 是兩台裝置存取這一桶的鑰匙；資料本身還會再用你的密語加密，token 外洩只拿得到密文。"
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "在 R2 Overview 右側「Account Details」的 API Tokens 旁按「Manage」（上面連結通常直接到這頁）。"
step "選「Create User API token」（或「Create Account API token」，兩種都可；User token 換帳號就失效，自用選它即可）。"
step "Token name 填 next-stop-sync。"
step "Permissions 選「Object Read & Write」。"
step "「Specify bucket(s)」勾 Apply to specific buckets only，選剛建的 ${R2_BUCKET}。"
step "TTL 若有選項選 Forever／不設期限；Client IP 留空。"
step "按「Create User API token」。"
warn "官方原文：「You will not be able to access your Secret Access Key again after this step.」——這頁離開就看不到 Secret 了，先貼進來再關頁。"
step "頁面會顯示 Access Key ID、Secret Access Key、以及 endpoint https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com。"
ask R2_ACCESS_KEY_ID "貼上 Access Key ID："
ask_secret R2_SECRET_ACCESS_KEY "貼上 Secret Access Key（輸入不會顯示）："
while [[ -z "$R2_ACCESS_KEY_ID" || -z "$R2_SECRET_ACCESS_KEY" ]]; do
  warn "兩個都要有。"
  ask R2_ACCESS_KEY_ID "貼上 Access Key ID："
  ask_secret R2_SECRET_ACCESS_KEY "貼上 Secret Access Key："
done
R2_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

# ── Stage 4：用 curl 實際列一次桶，確認鑰匙能開 ─────────────────────────────
stage "驗證：用這把 token 列一次 bucket"
say "curl 內建 AWS SigV4 簽章，直接對 R2 的 S3 端點做一次 ListObjects——回 200 就代表帳號／桶／token 三者對得上。"
code=$(curl -s -o /dev/null -w '%{http_code}' \
  --aws-sigv4 "aws:amz:auto:s3" --user "${R2_ACCESS_KEY_ID}:${R2_SECRET_ACCESS_KEY}" \
  "${R2_ENDPOINT}/${R2_BUCKET}?list-type=2&max-keys=1" || echo "000")
if [[ "$code" == "200" ]]; then
  printf '  %s✓ 通了%s（HTTP 200）：token 能讀寫 %s\n' "$GREEN" "$RESET" "$R2_BUCKET"
  write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
  write_env R2_BUCKET "$R2_BUCKET"
  write_env R2_ENDPOINT "$R2_ENDPOINT"
  write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
  write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
  note "檔案：$ENV_FILE（只有這台電腦看得到；請勿丟進 repo 或聊天視窗）"
else
  warn "HTTP $code——沒通。常見原因：403＝token 權限不含這一桶或 Secret 貼錯；404＝bucket 名稱打錯；000＝離線。"
  if confirm "還是要先把值存起來（之後可重跑本精靈驗證）？"; then
    write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"; write_env R2_BUCKET "$R2_BUCKET"; write_env R2_ENDPOINT "$R2_ENDPOINT"
    write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"; write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
  fi
  SKIPPED+=("驗證未通過（HTTP $code）：到 R2 › Manage API tokens 檢查權限與桶，然後重跑 bash scripts/setup-r2.sh")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
